# Generated by Django 5.2.16 on 2026-08-10 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('event_name', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('info', 'Info')], db_index=True, default='info', max_length=20)),
                ('page', models.CharField(blank=True, default='', max_length=120)),
                ('source', models.CharField(blank=True, default='backend', max_length=40)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_name', 'created_at'], name='analytics_a_event_n_e2acee_idx'), models.Index(fields=['status', 'created_at'], name='analytics_a_status_bfca3c_idx')],
            },
        ),
    ]
