# Generated by Django 5.2.15 on 2026-08-03 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('civil', 'Civil'), ('criminal', 'Criminal'), ('family', 'Family'), ('corporate', 'Corporate')], max_length=255)),
                ('case_id', models.CharField(max_length=255, unique=True)),
                ('case_title', models.CharField(max_length=255)),
                ('case_status', models.CharField(choices=[('active', 'Active'), ('hearing', 'Hearing'), ('closed', 'Closed')], max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('opposing_party_name', models.CharField(max_length=255)),
                ('court_name', models.CharField(max_length=255)),
                ('hearing_date', models.DateField()),
                ('case_description', models.TextField()),
                ('case_created_at', models.DateTimeField(auto_now_add=True)),
                ('case_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='case_management.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=255)),
                ('note_content', models.TextField()),
                ('note_created_at', models.DateTimeField(auto_now_add=True)),
                ('note_updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='case_management.case')),
            ],
        ),
    ]
