# Generated by Django 5.2.15 on 2026-08-04 07:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocuments',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='case_documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='casedocuments',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casedocuments',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateField()),
                ('hearing_time', models.TimeField(blank=True, null=True)),
                ('court_name', models.CharField(blank=True, max_length=255)),
                ('judge_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('urgent', 'Urgent'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('hearing_created_at', models.DateTimeField(auto_now_add=True)),
                ('hearing_updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='case_management.case')),
            ],
            options={
                'ordering': ['hearing_date', 'hearing_time'],
            },
        ),
    ]
