# Generated by Django 5.2.16 on 2026-08-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0002_casedocuments_document_file_casedocuments_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocuments',
            name='chunk_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casedocuments',
            name='embedded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casedocuments',
            name='embedding_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casedocuments',
            name='embedding_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
