# Generated by Django 5.2.16 on 2026-08-05 05:31

from django.db import migrations, models


def migrate_hearing_status_to_active(apps, schema_editor):
    """'hearing' is being removed as a case-level status (see model comment),
    so any case still carrying it becomes 'active' — it's still an open
    case, just tracked via the Hearing model going forward."""
    Case = apps.get_model('case_management', 'Case')
    Case.objects.filter(case_status='hearing').update(case_status='active')


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0003_casedocuments_chunk_count_casedocuments_embedded_at_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_hearing_status_to_active, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], max_length=255),
        ),
    ]
